

SELECT
	T1.PROD_CODE As 商品コード
	,T1.PROD_NAME As 商品名
	,T1.PROD_SHORT_NAME As 商品略名
	,T1.PROD_KANA_NAME As 商品カナ名
	,T6.UNIT_GRP_NAME As 単位名称
	,T1.WEIGHT As 重量
	,CASE ISNULL(T2.NEW_PU_PLAN_PRICE, 999999999) WHEN 999999999 THEN NULL ELSE T2.PU_PLAN_PRICE END As 旧仕入予定単価
	,ISNULL(T2.NEW_PU_PLAN_PRICE, T2.PU_PLAN_PRICE) As 最新仕入予定単価
	,CASE ISNULL(T2.NEW_INHOUSE_SELL_PRICE, 999999999) WHEN 999999999 THEN NULL ELSE T2.INHOUSE_SELL_PRICE END As 表示用原価
	,ISNULL(T2.NEW_INHOUSE_SELL_PRICE, T2.INHOUSE_SELL_PRICE) As 新表示用原価
	,T2.PRICE_CHANGE_DATE As 原価単価改定日
	---------------------------------------------------------------------------------------------------------
	,CASE ISNULL(T3.NEW_SELL_PRICE, 999999999) WHEN 999999999 THEN NULL ELSE T3.SELL_PRICE END As '販売単価(000)'
	,ISNULL(T3.NEW_SELL_PRICE, T3.SELL_PRICE) As '新販売単価(000)'
	,CASE ISNULL(T20.NEW_SELL_PRICE, 999999999) WHEN 999999999 THEN NULL ELSE T20.SELL_PRICE END As '販売単価(001)'
	,ISNULL(T20.NEW_SELL_PRICE, T20.SELL_PRICE) As '新販売単価(001)'
	,T3.SELL_PRICE_CHANGE_DATE As 販売単価改定日
	---------------------------------------------------------------------------------------------------------
	,SUBSTRING(T7.SEGMENT_CODE, 1, 2) As [大分類]
	,T8.SEGMENT_NAME As [大分類名]
	,SUBSTRING(T7.SEGMENT_CODE, 1, 4) As [中分類]
	,T9.SEGMENT_NAME As [中分類名]
	,T7.SEGMENT_CODE As [小分類]
	,T10.SEGMENT_NAME As [小分類名]
	,T1.PROD_SERIES_CODE As シリーズコード
	,T12.PROD_SERIES_NAME As シリーズ名
	,PROD_INFORMATION.SORT As ソート
	,T1.SAFE_STOCK_QT AS スポット数
	,T1.SET_QT AS 結束数
	,T1.PROD_ENG_NAME AS 英字名
	---------------------------------------------------------------------------------------------------------
	,T13.VALID_QT AS 有効在庫
	,CASE WHEN PROD_INFORMATION.NEW_INDICATE_FLG IS NULL THEN '対象外'
		WHEN PROD_INFORMATION.NEW_INDICATE_FLG = '0' THEN '社内のみ'
		WHEN PROD_INFORMATION.NEW_INDICATE_FLG = '1' THEN '社外'
		WHEN PROD_INFORMATION.NEW_INDICATE_FLG = '対象外' THEN '対象外'
		WHEN PROD_INFORMATION.NEW_INDICATE_FLG = '無し' THEN '対象外'
		WHEN PROD_INFORMATION.NEW_INDICATE_FLG = '保留' THEN '保留'
		WHEN PROD_INFORMATION.NEW_INDICATE_FLG = '新検討' THEN '新検討'
		ELSE 'その他' END AS 価格表掲載区分
	,CASE WHEN ITEM.EC_SELL <> '0' AND ITEM.EC_COST_PRICE <>  '0' AND ITEM_DTIL.TEIKA <> '0' THEN '掲載' 
   		ELSE '非掲載' END EC掲載区分
   
   
FROM
    PROD T1 WITH (NOLOCK)
    LEFT OUTER JOIN UNIT_SPEC_PROD_ATTRIBUTE T2 WITH (NOLOCK) ON
                                    T2.PROD_CODE = T1.PROD_CODE
                                AND T2.PROD_SPEC_1_CODE = '999'
                                AND T2.PROD_SPEC_2_CODE = '999'
                                AND T2.UNIT_CODE = '000'
    LEFT OUTER JOIN PROD_PRICE_LIST_DTIL T3 WITH (NOLOCK) ON
                                    T3.PROD_PRICE_LIST_NO = '500705'
                                AND T3.PROD_CODE = T1.PROD_CODE
                                AND T3.PROD_SPEC_1_CODE = '999'
                                AND T3.PROD_SPEC_2_CODE = '999'
                                AND T3.UNIT_CODE = '000'
------------------------------------------------------------------------------------------
--20171222_001を追加								
	LEFT OUTER JOIN PROD_PRICE_LIST_DTIL T20 WITH (NOLOCK) ON
                                    T20.PROD_PRICE_LIST_NO = '500705'
                                AND T20.PROD_CODE = T1.PROD_CODE
                                AND T20.PROD_SPEC_1_CODE = '999'
                                AND T20.PROD_SPEC_2_CODE = '999'
                                AND T20.UNIT_CODE = '001'

								
								
    LEFT OUTER JOIN UNIT_GRP T6 WITH (NOLOCK) ON T6.UNIT_GRP_CODE = T1.UNIT_GRP_CODE AND T6.STOCK_DISP_UNIT_CODE = '000'
    LEFT OUTER JOIN R_1_1_0_CM.dbo.PROD_SEGMENT T7 WITH (NOLOCK) ON T7.PROD_CODE = T1.PROD_CODE AND T7.CATEGORY_CODE = '60P'
    LEFT OUTER JOIN R_1_1_0_CM.dbo.SEGMENT T8 WITH (NOLOCK) ON T8.CATEGORY_CODE = '60P' AND T8.SEGMENT_CODE = SUBSTRING(T7.SEGMENT_CODE, 1, 2)
    LEFT OUTER JOIN R_1_1_0_CM.dbo.SEGMENT T9 WITH (NOLOCK) ON T9.CATEGORY_CODE = '60P' AND T9.SEGMENT_CODE = SUBSTRING(T7.SEGMENT_CODE, 1, 4)
    LEFT OUTER JOIN R_1_1_0_CM.dbo.SEGMENT T10 WITH (NOLOCK) ON T10.CATEGORY_CODE = '60P' AND T10.SEGMENT_CODE = T7.SEGMENT_CODE
    LEFT OUTER JOIN (SELECT DISTINCT
							CUST_PROD_ATTRIBUTE.PROD_CODE AS PROD_CODE,
    						'1' AS HC_FLG
					FROM
							CUST_PROD_ATTRIBUTE WITH (NOLOCK)
					WHERE
						CUST_PROD_ATTRIBUTE.CUST_CODE in ('00001047','00001053','00001096','00001655','00002258','00010537','00004974'))T11 ON
		T11.PROD_CODE = T1.PROD_CODE
    LEFT OUTER JOIN (SELECT
    						TF_PROD_SERIES.PROD_SERIES_CODE AS PROD_SERIES_CODE,
                            TF_PROD_SERIES.PROD_SERIES_NAME AS PROD_SERIES_NAME
    					FROM TF_PROD_SERIES WITH (NOLOCK))T12 ON
    	T12.PROD_SERIES_CODE = T1.PROD_SERIES_CODE
	LEFT OUTER JOIN "SBI012\TAIYO".PRICE.DBO.PROD_INFORMATION PROD_INFORMATION WITH (NOLOCK) ON
		PROD_INFORMATION.PROD_CODE = T1.PROD_CODE
		
	--20220826_有効在庫を追加
	LEFT OUTER JOIN (SELECT
						STOCK.PROD_CODE AS PROD_CODE
						,SUM(STOCK.VALID_QT) AS VALID_QT
					
					FROM
						STOCK WITH (NOLOCK)
						INNER JOIN PROD WITH (NOLOCK) ON
							PROD.PROD_CODE = STOCK.PROD_CODE
					WHERE
						STOCK.WH_CODE = '027C7'
					AND PROD.TEMP_PROD_FLG = '0'
					GROUP BY
						STOCK.PROD_CODE)T13 ON
		T13.PROD_CODE = T1.PROD_CODE
	
	--20220828_ECサイト掲載区分を追加
	LEFT OUTER JOIN EC_EBIS.DBO.ITEM ITEM WITH (NOLOCK) ON
		ITEM.PROD_CODE = T1.PROD_CODE
	LEFT OUTER JOIN EC_EBIS.DBO.ITEM_DTIL ITEM_DTIL WITH (NOLOCK) ON
		ITEM_DTIL.ITEM_CD = T1.PROD_CODE
		
		
WHERE
    T1.VALID_FLG = '1'
AND (T1.PROD_CODE LIKE '1%' OR T1.PROD_CODE LIKE '3%' OR T1.PROD_CODE LIKE '2%' OR T1.PROD_CODE LIKE '4%')
AND T1.TEMP_PROD_FLG = '0'
ORDER BY
	CASE WHEN T1.SPECIFIC_ITEM1 IS NULL THEN LEFT(T1.PROD_CODE,1) + T7.SEGMENT_CODE + '99999999' ELSE T1.SPECIFIC_ITEM1 END
